version: "3.3"
services:

  authcontainer:
    container_name: authcontainer
    hostname: authcontainer
    image: authcontainer
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4000:4000

