version: "3.3"
services:
  mongo:
    image: mongo
    container_name: mongo
    # command: mongod --port 27027
    ports:
      - 27017:27017
    # environment:
    # MONGO_INITDB_ROOT_USERNAME: admin
    # MONGO_INITDB_ROOT_PASSWORD: foobar
    # MONGO_INITDB_DATABASE: db
    # volumes:
    # - /etc/mongod.conf:/etc/mongod.conf.orig
    restart: always

  microservice:
    container_name: microservice
    image: microservice:1.0.0
    build:
      context: ./microservice
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - 3000:3000
    # volumes:
    # - api-logs:/var/local/applogs
    environment:
      - database='mongodb://mongo/user-authenticity'
    restart: always

  clientproxy:
    container_name: clientproxy
    image: clientproxy:1.0.0
    build:
      context: ./clientproxy
      dockerfile: Dockerfile
    depends_on:
      - microservice
    ports:
      - 4000:4000
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm run start:debug'
    restart: always
